"""提示词模板模块"""

from .templates import (
    PERSONA_GENERATION_PROMPT,
    QUERY_GENERATION_PROMPT,
    DEEP_RESEARCH_FILTER_PROMPT,
    NO_SEARCH_BASELINE_PROMPT,
    QUALITY_ASSESSMENT_PROMPT,
    render_prompt,
)

__all__ = [
    "PERSONA_GENERATION_PROMPT",
    "QUERY_GENERATION_PROMPT",
    "DEEP_RESEARCH_FILTER_PROMPT",
    "NO_SEARCH_BASELINE_PROMPT",
    "QUALITY_ASSESSMENT_PROMPT",
    "render_prompt",
]

